pub(crate) mod dma;
pub(crate) mod game_port;
pub(crate) mod keyboard;
pub(crate) mod mock_com_device;
pub(crate) mod mouse;
pub(crate) mod parallel_port_loopback;
pub(crate) mod pit;
pub(crate) mod serial_loopback;
pub(crate) mod uart;
