use std::fmt;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Mnemonic {
    // Data transfer
    Mov,
    Push,
    Pop,
    Xchg,
    In,
    Out,
    Xlat,
    Lea,
    Lds,
    Les,
    Lahf,
    Sahf,
    Pushf,
    Popf,
    // Arithmetic
    Add,
    Adc,
    Sub,
    Sbb,
    Inc,
    Dec,
    Neg,
    Cmp,
    Mul,
    IMul,
    Div,
    IDiv,
    Cbw,
    Cwd,
    Daa,
    Das,
    Aaa,
    Aas,
    Aam,
    Aad,
    // Logic
    And,
    Or,
    Xor,
    Not,
    Test,
    // Shift / rotate
    Shl,
    Shr,
    Sar,
    Rol,
    Ror,
    Rcl,
    Rcr,
    // String ops
    Movsb,
    Movsw,
    Cmpsb,
    Cmpsw,
    Scasb,
    Scasw,
    Lodsb,
    Lodsw,
    Stosb,
    Stosw,
    // Control transfer
    Call,
    CallFar,
    Ret,
    RetFar,
    Jmp,
    JmpFar,
    Ja,
    Jae,
    Jb,
    Jbe,
    Jcxz,
    Je,
    Jg,
    Jge,
    Jl,
    Jle,
    Jne,
    Jno,
    Jns,
    Jo,
    Jp,
    Jnp,
    Js,
    Loop,
    Loopz,
    Loopnz,
    // Interrupt
    Int,
    Int3,
    Into,
    Iret,
    // Processor control
    Nop,
    Hlt,
    Wait,
    Lock,
    Cli,
    Sti,
    Cld,
    Std,
    Clc,
    Stc,
    Cmc,
    // Prefixes
    Rep,
    Repne,
    // Unknown / unimplemented
    Unknown(u8),
}

impl fmt::Display for Mnemonic {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            Mnemonic::Mov => "mov",
            Mnemonic::Push => "push",
            Mnemonic::Pop => "pop",
            Mnemonic::Xchg => "xchg",
            Mnemonic::In => "in",
            Mnemonic::Out => "out",
            Mnemonic::Xlat => "xlat",
            Mnemonic::Lea => "lea",
            Mnemonic::Lds => "lds",
            Mnemonic::Les => "les",
            Mnemonic::Lahf => "lahf",
            Mnemonic::Sahf => "sahf",
            Mnemonic::Pushf => "pushf",
            Mnemonic::Popf => "popf",
            Mnemonic::Add => "add",
            Mnemonic::Adc => "adc",
            Mnemonic::Sub => "sub",
            Mnemonic::Sbb => "sbb",
            Mnemonic::Inc => "inc",
            Mnemonic::Dec => "dec",
            Mnemonic::Neg => "neg",
            Mnemonic::Cmp => "cmp",
            Mnemonic::Mul => "mul",
            Mnemonic::IMul => "imul",
            Mnemonic::Div => "div",
            Mnemonic::IDiv => "idiv",
            Mnemonic::Cbw => "cbw",
            Mnemonic::Cwd => "cwd",
            Mnemonic::Daa => "daa",
            Mnemonic::Das => "das",
            Mnemonic::Aaa => "aaa",
            Mnemonic::Aas => "aas",
            Mnemonic::Aam => "aam",
            Mnemonic::Aad => "aad",
            Mnemonic::And => "and",
            Mnemonic::Or => "or",
            Mnemonic::Xor => "xor",
            Mnemonic::Not => "not",
            Mnemonic::Test => "test",
            Mnemonic::Shl => "shl",
            Mnemonic::Shr => "shr",
            Mnemonic::Sar => "sar",
            Mnemonic::Rol => "rol",
            Mnemonic::Ror => "ror",
            Mnemonic::Rcl => "rcl",
            Mnemonic::Rcr => "rcr",
            Mnemonic::Movsb => "movsb",
            Mnemonic::Movsw => "movsw",
            Mnemonic::Cmpsb => "cmpsb",
            Mnemonic::Cmpsw => "cmpsw",
            Mnemonic::Scasb => "scasb",
            Mnemonic::Scasw => "scasw",
            Mnemonic::Lodsb => "lodsb",
            Mnemonic::Lodsw => "lodsw",
            Mnemonic::Stosb => "stosb",
            Mnemonic::Stosw => "stosw",
            Mnemonic::Call => "call",
            Mnemonic::CallFar => "call far",
            Mnemonic::Ret => "ret",
            Mnemonic::RetFar => "retf",
            Mnemonic::Jmp => "jmp",
            Mnemonic::JmpFar => "jmp far",
            Mnemonic::Ja => "ja",
            Mnemonic::Jae => "jae",
            Mnemonic::Jb => "jb",
            Mnemonic::Jbe => "jbe",
            Mnemonic::Jcxz => "jcxz",
            Mnemonic::Je => "je",
            Mnemonic::Jg => "jg",
            Mnemonic::Jge => "jge",
            Mnemonic::Jl => "jl",
            Mnemonic::Jle => "jle",
            Mnemonic::Jne => "jne",
            Mnemonic::Jno => "jno",
            Mnemonic::Jns => "jns",
            Mnemonic::Jo => "jo",
            Mnemonic::Jp => "jp",
            Mnemonic::Jnp => "jnp",
            Mnemonic::Js => "js",
            Mnemonic::Loop => "loop",
            Mnemonic::Loopz => "loopz",
            Mnemonic::Loopnz => "loopnz",
            Mnemonic::Int => "int",
            Mnemonic::Int3 => "int3",
            Mnemonic::Into => "into",
            Mnemonic::Iret => "iret",
            Mnemonic::Nop => "nop",
            Mnemonic::Hlt => "hlt",
            Mnemonic::Wait => "wait",
            Mnemonic::Lock => "lock",
            Mnemonic::Cli => "cli",
            Mnemonic::Sti => "sti",
            Mnemonic::Cld => "cld",
            Mnemonic::Std => "std",
            Mnemonic::Clc => "clc",
            Mnemonic::Stc => "stc",
            Mnemonic::Cmc => "cmc",
            Mnemonic::Rep => "rep",
            Mnemonic::Repne => "repne",
            Mnemonic::Unknown(b) => return write!(f, "db 0x{:02x}", b),
        };
        f.write_str(s)
    }
}
