use std::fmt;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Mnemonic {
    // Data transfer
    Mov,
    Push,
    Pop,
    Xchg,
    In,
    Out,
    Xlat,
    Lea,
    Lds,
    Les,
    Lahf,
    Sahf,
    Pushf,
    Popf,
    // Arithmetic
    Add,
    Adc,
    Sub,
    Sbb,
    Inc,
    Dec,
    Neg,
    Cmp,
    Mul,
    IMul,
    Div,
    IDiv,
    Cbw,
    Cwd,
    Daa,
    Das,
    Aaa,
    Aas,
    Aam,
    Aad,
    // Logic
    And,
    Or,
    Xor,
    Not,
    Test,
    // Shift / rotate
    Shl,
    Shr,
    Sar,
    Rol,
    Ror,
    Rcl,
    Rcr,
    // String ops
    Movsb,
    Movsw,
    Cmpsb,
    Cmpsw,
    Scasb,
    Scasw,
    Lodsb,
    Lodsw,
    Stosb,
    Stosw,
    // Control transfer
    Call,
    CallFar,
    Ret,
    RetFar,
    Jmp,
    JmpShort,
    JmpFar,
    Ja,
    Jae,
    Jb,
    Jbe,
    Jcxz,
    Je,
    Jg,
    Jge,
    Jl,
    Jle,
    Jne,
    Jno,
    Jns,
    Jo,
    Jp,
    Jnp,
    Js,
    Loop,
    Loopz,
    Loopnz,
    // Interrupt
    Int,
    Int3,
    Into,
    Iret,
    // Processor control
    Nop,
    Hlt,
    Wait,
    Lock,
    Cli,
    Sti,
    Cld,
    Std,
    Clc,
    Stc,
    Cmc,
    // Prefixes
    Rep,
    Repne,
    // FPU (8087 co-processor)
    // Control
    Fninit,
    Fnclex,
    Fsetpm,
    Fnstsw,
    Fldcw,
    Fnstcw,
    Fnsave,
    Frstor,
    Fnstenv,
    Fldenv,
    // Data transfer
    Fld,
    Fst,
    Fstp,
    // Load constants
    Fld1,
    Fldl2t,
    Fldl2e,
    Fldpi,
    Fldlg2,
    Fldln2,
    Fldz,
    // Arithmetic
    Fadd,
    Faddp,
    Fmul,
    Fmulp,
    Fsub,
    Fsubp,
    Fsubr,
    Fsubrp,
    Fdiv,
    Fdivp,
    Fdivr,
    Fdivrp,
    // Integer arithmetic
    Fiadd,
    Fimul,
    Ficom,
    Ficomp,
    Fisub,
    Fisubr,
    Fidiv,
    Fidivr,
    // Integer memory transfer
    Fild,
    Fist,
    Fistp,
    Fbld,
    Fbstp,
    // Comparison
    Fcom,
    Fcomp,
    Fcompp,
    Ftst,
    Fxam,
    // Stack / register
    Fxch,
    Ffree,
    Fdecstp,
    Fincstp,
    // Transcendental
    F2xm1,
    Fyl2x,
    Fptan,
    Fpatan,
    Fyl2xp1,
    // Misc
    Fabs,
    Fchs,
    Fsqrt,
    Frndint,
    Fxtract,
    Fprem,
    Fscale,
    // 286 undocumented
    Loadall,
    // Unknown / unimplemented
    Unknown(u8),
}

impl fmt::Display for Mnemonic {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            Mnemonic::Mov => "mov",
            Mnemonic::Push => "push",
            Mnemonic::Pop => "pop",
            Mnemonic::Xchg => "xchg",
            Mnemonic::In => "in",
            Mnemonic::Out => "out",
            Mnemonic::Xlat => "xlat",
            Mnemonic::Lea => "lea",
            Mnemonic::Lds => "lds",
            Mnemonic::Les => "les",
            Mnemonic::Lahf => "lahf",
            Mnemonic::Sahf => "sahf",
            Mnemonic::Pushf => "pushf",
            Mnemonic::Popf => "popf",
            Mnemonic::Add => "add",
            Mnemonic::Adc => "adc",
            Mnemonic::Sub => "sub",
            Mnemonic::Sbb => "sbb",
            Mnemonic::Inc => "inc",
            Mnemonic::Dec => "dec",
            Mnemonic::Neg => "neg",
            Mnemonic::Cmp => "cmp",
            Mnemonic::Mul => "mul",
            Mnemonic::IMul => "imul",
            Mnemonic::Div => "div",
            Mnemonic::IDiv => "idiv",
            Mnemonic::Cbw => "cbw",
            Mnemonic::Cwd => "cwd",
            Mnemonic::Daa => "daa",
            Mnemonic::Das => "das",
            Mnemonic::Aaa => "aaa",
            Mnemonic::Aas => "aas",
            Mnemonic::Aam => "aam",
            Mnemonic::Aad => "aad",
            Mnemonic::And => "and",
            Mnemonic::Or => "or",
            Mnemonic::Xor => "xor",
            Mnemonic::Not => "not",
            Mnemonic::Test => "test",
            Mnemonic::Shl => "shl",
            Mnemonic::Shr => "shr",
            Mnemonic::Sar => "sar",
            Mnemonic::Rol => "rol",
            Mnemonic::Ror => "ror",
            Mnemonic::Rcl => "rcl",
            Mnemonic::Rcr => "rcr",
            Mnemonic::Movsb => "movsb",
            Mnemonic::Movsw => "movsw",
            Mnemonic::Cmpsb => "cmpsb",
            Mnemonic::Cmpsw => "cmpsw",
            Mnemonic::Scasb => "scasb",
            Mnemonic::Scasw => "scasw",
            Mnemonic::Lodsb => "lodsb",
            Mnemonic::Lodsw => "lodsw",
            Mnemonic::Stosb => "stosb",
            Mnemonic::Stosw => "stosw",
            Mnemonic::Call => "call",
            Mnemonic::CallFar => "call far",
            Mnemonic::Ret => "ret",
            Mnemonic::RetFar => "retf",
            Mnemonic::Jmp => "jmp",
            Mnemonic::JmpShort => "jmp short",
            Mnemonic::JmpFar => "jmp far",
            Mnemonic::Ja => "ja",
            Mnemonic::Jae => "jae",
            Mnemonic::Jb => "jb",
            Mnemonic::Jbe => "jbe",
            Mnemonic::Jcxz => "jcxz",
            Mnemonic::Je => "je",
            Mnemonic::Jg => "jg",
            Mnemonic::Jge => "jge",
            Mnemonic::Jl => "jl",
            Mnemonic::Jle => "jle",
            Mnemonic::Jne => "jne",
            Mnemonic::Jno => "jno",
            Mnemonic::Jns => "jns",
            Mnemonic::Jo => "jo",
            Mnemonic::Jp => "jp",
            Mnemonic::Jnp => "jnp",
            Mnemonic::Js => "js",
            Mnemonic::Loop => "loop",
            Mnemonic::Loopz => "loopz",
            Mnemonic::Loopnz => "loopnz",
            Mnemonic::Int => "int",
            Mnemonic::Int3 => "int3",
            Mnemonic::Into => "into",
            Mnemonic::Iret => "iret",
            Mnemonic::Nop => "nop",
            Mnemonic::Hlt => "hlt",
            Mnemonic::Wait => "wait",
            Mnemonic::Lock => "lock",
            Mnemonic::Cli => "cli",
            Mnemonic::Sti => "sti",
            Mnemonic::Cld => "cld",
            Mnemonic::Std => "std",
            Mnemonic::Clc => "clc",
            Mnemonic::Stc => "stc",
            Mnemonic::Cmc => "cmc",
            Mnemonic::Rep => "rep",
            Mnemonic::Repne => "repne",
            // FPU
            Mnemonic::Fninit => "fninit",
            Mnemonic::Fnclex => "fnclex",
            Mnemonic::Fsetpm => "fsetpm",
            Mnemonic::Fnstsw => "fnstsw",
            Mnemonic::Fldcw => "fldcw",
            Mnemonic::Fnstcw => "fnstcw",
            Mnemonic::Fnsave => "fnsave",
            Mnemonic::Frstor => "frstor",
            Mnemonic::Fnstenv => "fnstenv",
            Mnemonic::Fldenv => "fldenv",
            Mnemonic::Fld => "fld",
            Mnemonic::Fst => "fst",
            Mnemonic::Fstp => "fstp",
            Mnemonic::Fld1 => "fld1",
            Mnemonic::Fldl2t => "fldl2t",
            Mnemonic::Fldl2e => "fldl2e",
            Mnemonic::Fldpi => "fldpi",
            Mnemonic::Fldlg2 => "fldlg2",
            Mnemonic::Fldln2 => "fldln2",
            Mnemonic::Fldz => "fldz",
            Mnemonic::Fadd => "fadd",
            Mnemonic::Faddp => "faddp",
            Mnemonic::Fmul => "fmul",
            Mnemonic::Fmulp => "fmulp",
            Mnemonic::Fsub => "fsub",
            Mnemonic::Fsubp => "fsubp",
            Mnemonic::Fsubr => "fsubr",
            Mnemonic::Fsubrp => "fsubrp",
            Mnemonic::Fdiv => "fdiv",
            Mnemonic::Fdivp => "fdivp",
            Mnemonic::Fdivr => "fdivr",
            Mnemonic::Fdivrp => "fdivrp",
            Mnemonic::Fiadd => "fiadd",
            Mnemonic::Fimul => "fimul",
            Mnemonic::Ficom => "ficom",
            Mnemonic::Ficomp => "ficomp",
            Mnemonic::Fisub => "fisub",
            Mnemonic::Fisubr => "fisubr",
            Mnemonic::Fidiv => "fidiv",
            Mnemonic::Fidivr => "fidivr",
            Mnemonic::Fild => "fild",
            Mnemonic::Fist => "fist",
            Mnemonic::Fistp => "fistp",
            Mnemonic::Fbld => "fbld",
            Mnemonic::Fbstp => "fbstp",
            Mnemonic::Fcom => "fcom",
            Mnemonic::Fcomp => "fcomp",
            Mnemonic::Fcompp => "fcompp",
            Mnemonic::Ftst => "ftst",
            Mnemonic::Fxam => "fxam",
            Mnemonic::Fxch => "fxch",
            Mnemonic::Ffree => "ffree",
            Mnemonic::Fdecstp => "fdecstp",
            Mnemonic::Fincstp => "fincstp",
            Mnemonic::F2xm1 => "f2xm1",
            Mnemonic::Fyl2x => "fyl2x",
            Mnemonic::Fptan => "fptan",
            Mnemonic::Fpatan => "fpatan",
            Mnemonic::Fyl2xp1 => "fyl2xp1",
            Mnemonic::Fabs => "fabs",
            Mnemonic::Fchs => "fchs",
            Mnemonic::Fsqrt => "fsqrt",
            Mnemonic::Frndint => "frndint",
            Mnemonic::Fxtract => "fxtract",
            Mnemonic::Fprem => "fprem",
            Mnemonic::Fscale => "fscale",
            Mnemonic::Loadall => "loadall",
            Mnemonic::Unknown(b) => return write!(f, "db 0x{:02x}", b),
        };
        f.write_str(s)
    }
}
