// BIOS splash-screen logo.
//
// `generate_bios_logo` returns pre-decoded RGBA pixels embedded at compile
// time from `assets/logo.png` (decoded by `build.rs`).  The raw data is
// embedded via `include_bytes!` so no PNG decoder is needed at runtime.

// Width / height consts generated by build.rs from assets/logo.png
include!(concat!(env!("OUT_DIR"), "/logo_dims.rs"));

// ── Logo pixel provider ───────────────────────────────────────────────────────

/// Return the BIOS logo as `(rgba_pixels, width, height)`.
///
/// The raw RGBA8 pixel data is embedded at compile time — no PNG decoder is
/// needed at runtime.
pub fn generate_bios_logo() -> (&'static [u8], usize, usize) {
    (
        include_bytes!(concat!(env!("OUT_DIR"), "/logo_rgba.bin")),
        LOGO_PNG_WIDTH,
        LOGO_PNG_HEIGHT,
    )
}
