pub const SCAN_CODE_RELEASE: u8 = 0x80;
pub const SCAN_CODE_EXTENDED_PREFIX: u8 = 0xE0;
pub const SCAN_CODE_E1_PREFIX: u8 = 0xE1;

pub const SCAN_CODE_LEFT_SHIFT: u8 = 0x2A;
pub const SCAN_CODE_RIGHT_SHIFT: u8 = 0x36;
pub const SCAN_CODE_LEFT_SHIFT_RELEASE: u8 = SCAN_CODE_LEFT_SHIFT | SCAN_CODE_RELEASE; // 0xAA
pub const SCAN_CODE_RIGHT_SHIFT_RELEASE: u8 = SCAN_CODE_RIGHT_SHIFT | SCAN_CODE_RELEASE; // 0xB6
pub const SCAN_CODE_LEFT_CTRL: u8 = 0x1D;
pub const SCAN_CODE_LEFT_CTRL_RELEASE: u8 = SCAN_CODE_LEFT_CTRL | SCAN_CODE_RELEASE; // 0x9D
pub const SCAN_CODE_LEFT_ALT: u8 = 0x38;
pub const SCAN_CODE_LEFT_ALT_RELEASE: u8 = SCAN_CODE_LEFT_ALT | SCAN_CODE_RELEASE; // 0xB8
pub const SCAN_CODE_F12: u8 = 0x58;
