pub const SCAN_CODE_RELEASE: u8 = 0x80;

pub const SCAN_CODE_LEFT_SHIFT: u8 = 0x2A;
pub const SCAN_CODE_RIGHT_SHIFT: u8 = 0x36;
pub const SCAN_CODE_LEFT_SHIFT_RELEASE: u8 = SCAN_CODE_LEFT_SHIFT | SCAN_CODE_RELEASE; // 0xAA
pub const SCAN_CODE_RIGHT_SHIFT_RELEASE: u8 = SCAN_CODE_RIGHT_SHIFT | SCAN_CODE_RELEASE; // 0xB6
pub const SCAN_CODE_F12: u8 = 0x58;
